# serene v1.2.0 (check for update at https://github.com/isunjn/serene/releases)

base_url = "https://0xblockz.xyz"      # Domain name of your website
title = "0xBlockz"
description = "Welcome to 0xBlockz, a static blog dedicated to infosec 🖥️, malware dev 🏴, coding 🦀 and linux 🐧"
default_language = "en"
theme = "tranquil"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feeds = true                 # Whether to generate a feed file in root, read docs for more info about rss feed
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "tranquil-light", filename = "hl-light.css"},
    { theme = "tranquil-dark", filename = "hl-dark.css"},
]
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
insert_anchor_links = "left"
#=========================================================================================

[extra]

name = "0ryX"                         # Your name
id = "0xblockz"                           # Your id / username / handle
bio = "Welcome to 0xBlockz, a static blog dedicated to infosec 🖥️, malware dev 🏴, coding 🦀 and linux 🐧" # Your bio
avatar = "img/avatar.webp"            # Your avatar
links = [                             # Your links
    { name = "Codeberg", icon = "codeberg", url = "https://codeberg.org/0ryx" },
    { name = "Mastodon", icon = "mastodon", url = "https://kolektiva.social/@0xBlockz" },
    { name = "Email", icon = "email", url = "mailto:deepnet@cock.lu" },
]

nav_separator = " > "

display_id = true                     # Display your id on homepage
projects_page = true                  # Display projects page
blog_categorized = false               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar

toc = true                            # Whether to show Table-Of-Contents by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
copy = true                           # Whether to add a copy button on code blocks by default
back_to_top = true                    # Whether to show back-to-top button by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

call_to_action_footer = "<span style='color:#e29292;'>PGP Fingerprint: F55F AB7B 9E68 D2B0 6539 5839 272F 8AB4 739D 05F4</span>"

#footer_copyright = "© 2025 0ryX 🏴"
footer_credits = false                 # Whether to show "Powered by Zola and Serene" in footer

footer_privacy_text = "Privacy Policy"
footer_privacy = false
