[[projects]]
name = "PGP Public Key"
description = "This is my PGP public key if you would like to contact me"
tags = ["security"]
links = [
  { name = "PGP Key", url = "https://termbin.com/s1oe" },
  { name = "PGP Key", url = "https://raw.githubusercontent.com/0ryX/pgp-public-key/refs/heads/main/pgp.txt"}

]

[[projects]]
name = "Webring"
description = "This is a webring of ghosts 👻"
tags = ["webring"]
links = [
  { name = "Haunted Webring", url = "https://raw.githubusercontent.com/VVX7/haunted-webring/main/webring.txt"},
]
