[[projects]]
name = "My PGP Public Key"
description = "This is my PGP public key if you would like to contact me"
tags = ["security"]
links = [
  { name = "PGP Key", url = "https://termbin.com/s1oe" }
]

